C  ********************************************************************
C  * COMMON BLOCK DEFINITION                                          *
C  ********************************************************************
      COMMON /BLOCK1/ TIME,TSTEP
      COMMON /BLOCK2/ PBASE(10),H(10),R(10),XL(10),XD(10),XD1(10),
     1XQ(10),XQ1(10),TD1(10),TQ1(10),DAMP(10),C1(10),C2(10)
C      COMMON /BLOCK3/ AVRPRM(10,16)
C      REAL KA(10),KE(10),KF(10),TA(10),TE(10),TF(10),VRMIN(10),
C     1VRMAX(10),DUM(10,6)
C      EQUIVALENCE (AVRPRM(1,1),KA)
C      EQUIVALENCE (AVRPRM(2,1),KE)
C      EQUIVALENCE (AVRPRM(3,1),KF)
C      EQUIVALENCE (AVRPRM(4,1),TA)
C      EQUIVALENCE (AVRPRM(5,1),TE)
C      EQUIVALENCE (AVRPRM(6,1),TF)
C      EQUIVALENCE (AVRPRM(7,1),VRMIN)
C      EQUIVALENCE (AVRPRM(8,1),VRMAX)
      COMMON /BLOCK4/ TURPRM(10,16)
      COMMON /BLOCK5/ VT(10),CT(10),EF(10),PM(10)
      COMMON /BLOCK6/ PLUG(10,16),OUT(10,16),SAVE(10,16)
      COMMON /BLOCK7/ Y(11,11)
      COMMON /BLOCK8/ TYM(200),VAR(200,6),NT,NVAR
      COMMON /BLOCK9/ PRTVAR(10,20)
      REAL TIME,TSTEP
      REAL PBASE,H,R,XL,XD,XD1,XQ,XQ1,TD1,TQ1,DAMP,C1,C2
C      REAL AVRPRM,KA,KE,KF,TA,TE,TF,VRMIN,VRMAX,DUM
C      REAL AVRPRM
      REAL TURPRM
      COMPLEX VT,CT,EF,PM
      REAL PLUG,OUT,SAVE
      COMPLEX Y
      REAL TYM,VAR
      INTEGER NT,NVAR
      REAL PRTVAR
