C  ********************************************************************
C  * SUBROUTINE TO CALCULATE STATE VARIABLES FOR NEXT INCREMENT IN TIME
C  ********************************************************************
C
C  Copyright (c) 2013 IncSys (http://incsys.com)
C
C  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRENTY OF ANY KIND,
C  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRENTIES
C  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
C  NONINFRENGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
C  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
C  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
C  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
C  SOFTWARE.
C
      SUBROUTINE INT(NGEN)
      IMPLICIT NONE
      INCLUDE 'cblocks.inc'
      INTEGER I,J,NGEN,NFLAG
      IF(TIME .EQ. 0.0) GO TO 20
      DO 10 I=1,NGEN
      DO 10 J=1,16
10    SAVE(I,J)=PLUG(I,J)
      NFLAG=1
20    CONTINUE
      DO 30 I=1,NGEN
      DO 30 J=1,16
      OUT(I,J)=OUT(I,J)+PLUG(I,J)*TSTEP+(PLUG(I,J)-SAVE(I,J))*0.5*TSTEP
30    SAVE(I,J)=PLUG(I,J)
      RETURN
      END

