C  ********************************************************************
C  * SUBROUTINE TO CALCULATE EQUIVALENT Y MATRIX FOR INTERNAL
C  * GENERATOR BUSES.
C  ********************************************************************
      SUBROUTINE MATRIX(NGEN)
      COMMON /BLOCK2/ PBASE(10),H(10),R(10),XL(10),XD(10),XD1(10),
     1XQ(10),XQ1(10),TD1(10),TQ1(10),DAMP(10),C1(10),C2(10)
      COMMON /BLOCK7/ Y(11,11)
      COMPLEX Y,YFICT,CMPLX,CONJG
C  AUTMENT Y MATRIX WITH GENERATOR BUSES AND ELIMINATE TH
C  TERMINAL BUSES.
      N1=NGEN+1
      DO 80 I=1,NGEN
C  MOVE TERMINAL BUS TO OUTSIDE OF MATRIX
      Y(N1,N1)=Y(I,I)
      Y(I,I)=(0.0,0.0)
      DO 75 J=1,NGEN
C  MOVE ROW
      Y(N1,J)=Y(I,J)
      Y(I,J)=(0.0,0.0)
C  MOVE COLUMN
      Y(J,N1)=Y(J,I)
      Y(J,I)=(0.0,0.0)
75    CONTINUE
C  ADD IN GENERATOR BUS
      YFICT=CMPLX(R(I),-(XD1(I)+XQ1(I))/2.0)/(R(I)+XD1(I)*XQ1(I))
      Y(I,I)=YFICT
C  CHECK IF TERMINAL BUS IS GROUNDED.
      IF(CABS(Y(M1,N1)) .EQ. 0.0) GO TO 80
      Y(N1,N1)=Y(N1,N1)+YFICT
      Y(I,N1)=-YFICT
      Y(N1,I)=-YFICT
C  ELIMINATE THE TERMINAL BUS.
      DO 76 M=1,NGEN
      DO 76 N=M,NGEN
      Y(M,N)=Y(M,N)-Y(M,N1)*Y(N1,N)/Y(N1,N1)
      Y(N,M)=Y(M,N)
76    CONTINUE
80    CONTINUE
      RETURN
      END

