C  ********************************************************************
C  *  SUBROUTINE TO PRINTOUT SYSTEM VARIABLES                         *
C  ********************************************************************
C
C  Copyright (c) 2013 IncSys (http://incsys.com)
C
C  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRENTY OF ANY KIND,
C  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRENTIES
C  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
C  NONINFRENGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
C  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
C  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
C  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
C  SOFTWARE.
C
      SUBROUTINE OUTPUT(NGEN)
      IMPLICIT NONE
      INCLUDE 'cblocks.fpp'
      INTEGER NGEN,I,J
      IF(TIME .EQ. 0.0) WRITE(6,2000)
2000  FORMAT('1'//T42,'SIMULATED RESPONSES',//T4,'TIME  GEN  ROTOR   ',
     1'ROTOR    EQ''     ED''    TERM     ELEC-POWER     FIELD   ',
     2'MECH    SATN   AIR GAP'/T4,'SECS   NO  ANGLE   SPEED    ',
     3'VOLTS   VOLTS  VOLTS    REAL   IMAG    VOLTS   POWER  ',
     4'FACTOR   VOLTS'/)
      WRITE(6,1010) TIME
1010  FORMAT(' ',F7.3)
      DO 10 I=1,NGEN
      WRITE(6,1000) I,(PRTVAR(I,J),J=1,11)
1000  FORMAT(' ',8X,I3,F8.3,13F8.4)
10    CONTINUE
C  SET UP THE VARIABLES TO BE PLOTTED.
      NT=NT+1
      TYM(NT)=TIME
      VAR(NT,1)=PRTVAR(1,1)
      VAR(NT,2)=PRTVAR(1,5)
      VAR(NT,3)=PRTVAR(1,6)
      VAR(NT,4)=PRTVAR(1,8)
      RETURN
      END

